name: Self destruct stale repo

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/self-destruct.yml
  workflow_dispatch:

permissions:
  administration: write
  contents: read

jobs:
  delete-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete this repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api -X DELETE "repos/${{ github.repository }}"
